// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgJhjowr9khaT7CgvrE7rBSqKL-HBBNGc',
    appId: '1:956277930742:web:870d786b41fe4d07610ad7',
    messagingSenderId: '956277930742',
    projectId: 'tp-firebase-27ffe',
    authDomain: 'tp-firebase-27ffe.firebaseapp.com',
    storageBucket: 'tp-firebase-27ffe.appspot.com',
    measurementId: 'G-649FWX2K0X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwM1yZafWGxAwMQ4OVDzSkrRuDZ1Vpo8c',
    appId: '1:956277930742:android:d71ae43575af2ac9610ad7',
    messagingSenderId: '956277930742',
    projectId: 'tp-firebase-27ffe',
    storageBucket: 'tp-firebase-27ffe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLZFrVyP9hflrss_WYEyHXfGDd3OMAdBY',
    appId: '1:956277930742:ios:fbf901df095e26ae610ad7',
    messagingSenderId: '956277930742',
    projectId: 'tp-firebase-27ffe',
    storageBucket: 'tp-firebase-27ffe.appspot.com',
    iosBundleId: 'com.example.notes',
  );
}
